{% set name = "mediawikiapi" %}
{% set version = "1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mediawikiapi-{{ version }}.tar.gz
  sha256: 452205c2a82585f40e912ba54687affca474abfc6ae5aca16916680cd4a8035a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - pytest-vcr >=1.0.2,<2.0.0
    - sphinx <8.0.0,>=7.2.6
    - python >={{ python_min }},<4.0.0
    - beautifulsoup4 >=4.11.1,<5.0.0
    - requests >=2.28.1,<3.0.0
    - typing-extensions

test:
  imports:
    - mediawikiapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Wikipedia API on Python
  home: https://github.com/lehinevych/MediaWikiAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
